AllCops:
  TargetRubyVersion: 2.6.5
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'bin/bundle'
    - 'db/**/*'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'script/**/*'

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 99
  IgnoredPatterns: ['(\A|\s)#']

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
  Exclude:
    - 'config/routes.rb'
    - 'config/environments/*.rb'

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
